name: ghizlln
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.3.5
  get: ^4.6.5

  image_picker: ^1.0.4
 #firebase
  firebase_core: ^3.13.1
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6
  firebase_messaging: ^15.2.6
  firebase_auth: ^5.5.4
  google_sign_in: ^6.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/darkimg.png
  image_dark: assets/images/splash_screen_darkmode.png
  android: true
  ios: true
  android_12:
    color: "#FFFFFF"
    color_dark: "#272727"
    image: assets/images/darkimg.png
    image_dark: assets/images/splash_screen_darkmode.png
    web: false


flutter:
  uses-material-design: true
  assets:
    - assets/images/




fonts:
  - family: PoetsenOne
    fonts:
      - asset: assets/fonts/PoetsenOne-Regular.ttf
