// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzTbljlNNinOHjuu7DCSwD4Ex_uXfmK6c',
    appId: '1:180850784755:web:3ddde4ce00238484483a86',
    messagingSenderId: '180850784755',
    projectId: 'studium-5d550',
    authDomain: 'studium-5d550.firebaseapp.com',
    storageBucket: 'studium-5d550.firebasestorage.app',
    measurementId: 'G-40J1D53Z0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEbxrTpRzfVd1oxVvR-7B7IZvOeAPQkxw',
    appId: '1:180850784755:android:1fc22353d1ccade9483a86',
    messagingSenderId: '180850784755',
    projectId: 'studium-5d550',
    storageBucket: 'studium-5d550.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpg-nNKp4CdlXSDSzuxZwg-cexcWBCkHw',
    appId: '1:180850784755:ios:806e291909853136483a86',
    messagingSenderId: '180850784755',
    projectId: 'studium-5d550',
    storageBucket: 'studium-5d550.firebasestorage.app',
    iosBundleId: 'com.example.ghizlln',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpg-nNKp4CdlXSDSzuxZwg-cexcWBCkHw',
    appId: '1:180850784755:ios:806e291909853136483a86',
    messagingSenderId: '180850784755',
    projectId: 'studium-5d550',
    storageBucket: 'studium-5d550.firebasestorage.app',
    iosBundleId: 'com.example.ghizlln',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzTbljlNNinOHjuu7DCSwD4Ex_uXfmK6c',
    appId: '1:180850784755:web:e532a952be886746483a86',
    messagingSenderId: '180850784755',
    projectId: 'studium-5d550',
    authDomain: 'studium-5d550.firebaseapp.com',
    storageBucket: 'studium-5d550.firebasestorage.app',
    measurementId: 'G-NJ2YXX2T7K',
  );
}
